name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.7
    - name: Install e2fsprogs
      run: sudo apt-get install e2fsprogs
    - name: Setup filesystem
      run: sudo ./test.sh setup
    - name: Test
      run: ./test.sh run
    - name: Clear filesystem
      run: sudo ./test.sh clear
